//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext_ : DbContext
    {
        public DatabaseContext_()
            : base("name=DatabaseContext_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Machines> Machines { get; set; }
        public virtual DbSet<Points> Points { get; set; }
        public virtual DbSet<Variables> Variables { get; set; }
        public virtual DbSet<Measurement> Measurement { get; set; }
        public virtual DbSet<Multiple_data_select> Multiple_data_select { get; set; }
    }
}
