//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public Machines()
        {
            this.Measurement = new HashSet<Measurement>();
        }
    
        public string machineID { get; set; }
        public string descriptionMachine { get; set; }
        public double machineAccuracy { get; set; }
    
        public virtual ICollection<Measurement> Measurement { get; set; }
    }
}
