//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public System.DateTime time { get; set; }
        public int pointID { get; set; }
        public double value1 { get; set; }
        public double value2 { get; set; }
        public string machineID { get; set; }
        public int groupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Machines Machines { get; set; }
        public virtual Points Points { get; set; }
    }
}
