//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multiple_data_select
    {
        public System.DateTime time { get; set; }
        public int pointID { get; set; }
        public string description { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double value1 { get; set; }
        public double value2 { get; set; }
        public double PointAccuracy { get; set; }
        public int variableID { get; set; }
        public string variableName { get; set; }
        public string machineID { get; set; }
        public string descriptionMachine { get; set; }
        public double machineAccuracy { get; set; }
        public int groupID { get; set; }
        public string descriptionGroup { get; set; }
    }
}
